version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    image: 'postgres:12'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-test}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}'
      - 'POSTGRES_USER=${POSTGRES_USER:-test}'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '${POSTGRES_PORT:-24532}:5432'